config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :personal_records
  resources :workouts
  resources :set_of_exercises
  resources :exercises
  resources :home, only: :index

  authenticated :user do
    root 'workouts#index', as: :authenticated_root
  end

  root "home#index"
end

app/models/personal_record.rb
class PersonalRecord < ActiveRecord::Base
  belongs_to :user
  belongs_to :exercise
end

app/controllers/personal_records_controller.rb
class PersonalRecordsController < ApplicationController
  before_action :set_personal_record, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /personal_records
  # GET /personal_records.json
  def index
    @personal_records = PersonalRecord.all
  end

  # GET /personal_records/1
  # GET /personal_records/1.json
  def show
  end

  # GET /personal_records/new
  def new
    @personal_record = PersonalRecord.new
  end

  # GET /personal_records/1/edit
  def edit
  end

  # POST /personal_records
  # POST /personal_records.json
  def create
    @personal_record = PersonalRecord.new(personal_record_params)

    respond_to do |format|
      if @personal_record.save
        format.html { redirect_to @personal_record, notice: 'Personal record was successfully created.' }
        format.json { render :show, status: :created, location: @personal_record }
      else
        format.html { render :new }
        format.json { render json: @personal_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personal_records/1
  # PATCH/PUT /personal_records/1.json
  def update
    respond_to do |format|
      if @personal_record.update(personal_record_params)
        format.html { redirect_to @personal_record, notice: 'Personal record was successfully updated.' }
        format.json { render :show, status: :ok, location: @personal_record }
      else
        format.html { render :edit }
        format.json { render json: @personal_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personal_records/1
  # DELETE /personal_records/1.json
  def destroy
    @personal_record.destroy
    respond_to do |format|
      format.html { redirect_to personal_records_url, notice: 'Personal record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personal_record
      @personal_record = PersonalRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personal_record_params
      params.require(:personal_record).permit(:user_id, :exercise_id, :sets, :repititions, :one_rep_max)
    end
end

app/helpers/personal_records_helper.rb
module PersonalRecordsHelper
end

app/views/personal_records/_form.html.haml
= form_for(@personal_record) do |f|
  - if @personal_record.errors.any?
    #error_explanation
      %h2
        = pluralize(@personal_record.errors.count, "error")
        prohibited this personal_record from being saved:
      %ul
        - @personal_record.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :user_id
    %br/
    = f.text_field :user_id
  .field
    = f.label :exercise_id
    %br/
    = f.text_field :exercise_id
  .field
    = f.label :sets
    %br/
    = f.number_field :sets
  .field
    = f.label :repititions
    %br/
    = f.number_field :repititions
  .field
    = f.label :one_rep_max
    %br/
    = f.text_field :one_rep_max
  .actions
    = f.submit

app/views/personal_records/edit.html.haml
%h1 Editing Personal Record
= render 'form'
= link_to 'Show', @personal_record
|
= link_to 'Back', personal_records_path

app/views/personal_records/index.html.haml
%p#notice= notice
%h1 Listing Personal Records
%table
  %thead
    %tr
      %th User
      %th Exercise
      %th Sets
      %th Repititions
      %th One rep max
      %th{:colspan => "3"}
  %tbody
    - @personal_records.each do |personal_record|
      %tr
        %td= personal_record.user
        %td= personal_record.exercise
        %td= personal_record.sets
        %td= personal_record.repititions
        %td= personal_record.one_rep_max
        %td= link_to 'Show', personal_record
        %td= link_to 'Edit', edit_personal_record_path(personal_record)
        %td= link_to 'Destroy', personal_record, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Personal record', new_personal_record_path

app/views/personal_records/new.html.haml
%h1 New Personal Record
= render 'form'
= link_to 'Back', personal_records_path

app/views/personal_records/show.html.haml
%p#notice= notice
%p
  %strong User:
  = @personal_record.user
%p
  %strong Exercise:
  = @personal_record.exercise
%p
  %strong Sets:
  = @personal_record.sets
%p
  %strong Repititions:
  = @personal_record.repititions
%p
  %strong One rep max:
  = @personal_record.one_rep_max
= link_to 'Edit', edit_personal_record_path(@personal_record)
|
= link_to 'Back', personal_records_path