config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :personal_records
  resources :workouts
  resources :set_of_exercises
  resources :exercises
  resources :home, only: :index

  authenticated :user do
    root 'workouts#index', as: :authenticated_root
  end

  root "home#index"
end

app/controllers/set_of_exercises_controller.rb
class SetOfExercisesController < ApplicationController
  before_action :set_set_of_exercise, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /set_of_exercises
  # GET /set_of_exercises.json
  def index
    @set_of_exercises = SetOfExercise.all
  end

  # GET /set_of_exercises/1
  # GET /set_of_exercises/1.json
  def show
  end

  # GET /set_of_exercises/new
  def new
    @set_of_exercise = SetOfExercise.new
  end

  # GET /set_of_exercises/1/edit
  def edit
  end

  # POST /set_of_exercises
  # POST /set_of_exercises.json
  def create
    @set_of_exercise = SetOfExercise.new(set_of_exercise_params)

    respond_to do |format|
      if @set_of_exercise.save
        format.html { redirect_to @set_of_exercise, notice: 'Set of exercise was successfully created.' }
        format.json { render :show, status: :created, location: @set_of_exercise }
      else
        format.html { render :new }
        format.json { render json: @set_of_exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /set_of_exercises/1
  # PATCH/PUT /set_of_exercises/1.json
  def update
    respond_to do |format|
      if @set_of_exercise.update(set_of_exercise_params)
        format.html { redirect_to @set_of_exercise, notice: 'Set of exercise was successfully updated.' }
        format.json { render :show, status: :ok, location: @set_of_exercise }
      else
        format.html { render :edit }
        format.json { render json: @set_of_exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /set_of_exercises/1
  # DELETE /set_of_exercises/1.json
  def destroy
    @set_of_exercise.destroy
    respond_to do |format|
      format.html { redirect_to set_of_exercises_url, notice: 'Set of exercise was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_set_of_exercise
      @set_of_exercise = SetOfExercise.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def set_of_exercise_params
      params.require(:set_of_exercise).permit(:exercise_id, :weight, :reps)
    end
end

app/helpers/set_of_exercises_helper.rb
module SetOfExercisesHelper
end

app/views/set_of_exercises/_form.html.haml
= form_for(@set_of_exercise) do |f|
  - if @set_of_exercise.errors.any?
    #error_explanation
      %h2
        = pluralize(@set_of_exercise.errors.count, "error")
        prohibited this set_of_exercise from being saved:
      %ul
        - @set_of_exercise.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :exercise_id
    %br/
    = f.text_field :exercise_id
  .field
    = f.label :weight
    %br/
    = f.number_field :weight
  .field
    = f.label :reps
    %br/
    = f.number_field :reps
  .actions
    = f.submit

app/views/set_of_exercises/edit.html.haml
%h1 Editing Set Of Exercise
= render 'form'
= link_to 'Show', @set_of_exercise
|
= link_to 'Back', set_of_exercises_path

app/views/set_of_exercises/index.html.haml
%p#notice= notice
%h1 Listing Set Of Exercises
%table
  %thead
    %tr
      %th Exercise
      %th Weight
      %th Reps
      %th{:colspan => "3"}
  %tbody
    - @set_of_exercises.each do |set_of_exercise|
      %tr
        %td= set_of_exercise.exercise
        %td= set_of_exercise.weight
        %td= set_of_exercise.reps
        %td= link_to 'Show', set_of_exercise
        %td= link_to 'Edit', edit_set_of_exercise_path(set_of_exercise)
        %td= link_to 'Destroy', set_of_exercise, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Set of exercise', new_set_of_exercise_path

app/views/set_of_exercises/new.html.haml
%h1 New Set Of Exercise
= render 'form'
= link_to 'Back', set_of_exercises_path

app/views/set_of_exercises/show.html.haml
%p#notice= notice
%p
  %strong Exercise:
  = @set_of_exercise.exercise
%p
  %strong Weight:
  = @set_of_exercise.weight
%p
  %strong Reps:
  = @set_of_exercise.reps
= link_to 'Edit', edit_set_of_exercise_path(@set_of_exercise)
|
= link_to 'Back', set_of_exercises_path