config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :personal_records
  resources :workouts
  resources :set_of_exercises
  resources :exercises
  resources :home, only: :index

  authenticated :user do
    root 'workouts#index', as: :authenticated_root
  end

  root "home#index"
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  belongs_to :sets_of_exercises
  belongs_to :user
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /workouts
  # GET /workouts.json
  def index
    @workouts = Workout.all
  end

  # GET /workouts/1
  # GET /workouts/1.json
  def show
  end

  # GET /workouts/new
  def new
    @workout = Workout.new
  end

  # GET /workouts/1/edit
  def edit
  end

  # POST /workouts
  # POST /workouts.json
  def create
    @workout = Workout.new(workout_params)

    respond_to do |format|
      if @workout.save
        format.html { redirect_to @workout, notice: 'Workout was successfully created.' }
        format.json { render :show, status: :created, location: @workout }
      else
        format.html { render :new }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workouts/1
  # PATCH/PUT /workouts/1.json
  def update
    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to @workout, notice: 'Workout was successfully updated.' }
        format.json { render :show, status: :ok, location: @workout }
      else
        format.html { render :edit }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.json
  def destroy
    @workout.destroy
    respond_to do |format|
      format.html { redirect_to workouts_url, notice: 'Workout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workout_params
      params.require(:workout).permit(:sets_of_exercises_id, :user_id, :date)
    end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/_form.html.haml
= form_for(@workout) do |f|
  - if @workout.errors.any?
    #error_explanation
      %h2
        = pluralize(@workout.errors.count, "error")
        prohibited this workout from being saved:
      %ul
        - @workout.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :sets_of_exercises_id
    %br/
    = f.text_field :sets_of_exercises_id
  .field
    = f.label :user_id
    %br/
    = f.text_field :user_id
  .field
    = f.label :date
    %br/
    = f.datetime_select :date
  .actions
    = f.submit

app/views/workouts/edit.html.haml
%h1 Editing Workout
= render 'form'
= link_to 'Show', @workout
|
= link_to 'Back', workouts_path

app/views/workouts/index.html.haml
%p#notice= notice
%h1 Listing Workouts
%table
  %thead
    %tr
      %th Sets of exercises
      %th User
      %th Date
      %th{:colspan => "3"}
  %tbody
    - @workouts.each do |workout|
      %tr
        %td= workout.sets_of_exercises
        %td= workout.user
        %td= workout.date
        %td= link_to 'Show', workout
        %td= link_to 'Edit', edit_workout_path(workout)
        %td= link_to 'Destroy', workout, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Workout', new_workout_path

app/views/workouts/new.html.haml
%h1 New Workout
= render 'form'
= link_to 'Back', workouts_path

app/views/workouts/show.html.haml
%p#notice= notice
%p
  %strong Sets of exercises:
  = @workout.sets_of_exercises
%p
  %strong User:
  = @workout.user
%p
  %strong Date:
  = @workout.date
= link_to 'Edit', edit_workout_path(@workout)
|
= link_to 'Back', workouts_path