config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :personal_records
  resources :workouts
  resources :set_of_exercises
  resources :exercises
  resources :home, only: :index

  authenticated :user do
    root 'workouts#index', as: :authenticated_root
  end

  root "home#index"
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  # GET /exercises
  # GET /exercises.json
  def index
    @exercises = Exercise.all
  end

  # GET /exercises/1
  # GET /exercises/1.json
  def show
  end

  # GET /exercises/new
  def new
    @exercise = Exercise.new
  end

  # GET /exercises/1/edit
  def edit
  end

  # POST /exercises
  # POST /exercises.json
  def create
    @exercise = Exercise.new(exercise_params)

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to @exercise, notice: 'Exercise was successfully created.' }
        format.json { render :show, status: :created, location: @exercise }
      else
        format.html { render :new }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercises/1
  # PATCH/PUT /exercises/1.json
  def update
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to @exercise, notice: 'Exercise was successfully updated.' }
        format.json { render :show, status: :ok, location: @exercise }
      else
        format.html { render :edit }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercises/1
  # DELETE /exercises/1.json
  def destroy
    @exercise.destroy
    respond_to do |format|
      format.html { redirect_to exercises_url, notice: 'Exercise was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercise
      @exercise = Exercise.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exercise_params
      params.require(:exercise).permit(:name, :description)
    end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/exercises/_form.html.haml
= form_for(@exercise) do |f|
  - if @exercise.errors.any?
    #error_explanation
      %h2
        = pluralize(@exercise.errors.count, "error")
        prohibited this exercise from being saved:
      %ul
        - @exercise.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :description
    %br/
    = f.text_field :description
  .actions
    = f.submit

app/views/exercises/edit.html.haml
%h1 Editing Exercise
= render 'form'
= link_to 'Show', @exercise
|
= link_to 'Back', exercises_path

app/views/exercises/index.html.haml
%p#notice= notice
%h1 Listing Exercises
%table
  %thead
    %tr
      %th Name
      %th Description
      %th{:colspan => "3"}
  %tbody
    - @exercises.each do |exercise|
      %tr
        %td= exercise.name
        %td= exercise.description
        %td= link_to 'Show', exercise
        %td= link_to 'Edit', edit_exercise_path(exercise)
        %td= link_to 'Destroy', exercise, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Exercise', new_exercise_path

app/views/exercises/new.html.haml
%h1 New Exercise
= render 'form'
= link_to 'Back', exercises_path

app/views/exercises/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @exercise.name
%p
  %strong Description:
  = @exercise.description
= link_to 'Edit', edit_exercise_path(@exercise)
|
= link_to 'Back', exercises_path